### ISSUE TITLE
look at whether or not we need to set analysis thresh 0.8

### ISSUE THREAD

**Issue by beckermr** [esheldon/sxdes#7]

**Comment by esheldon** [comment]
Did we confirm this is what DESDM is using?

**Comment by esheldon** [comment]
What are the exact DESDM Y6 command line overrides for this?  https://github.com/des-science/eastlake/blob/main/eastlake/astromatic/Y6A1_v1_srcex.config

**Comment by beckermr** [comment]
I was just looking at this. The manual says:

```
Threshold (in surface brightness) at
which CLASS STAR and FWHM operate. 1 argument: relative to
Background RMS. 2 arguments: mu
(mag.arcsec−2
), Zero-point (mag).
```

**Comment by beckermr** [comment]
The command line overrides are here: 

https://github.com/des-science/eastlake/blob/main/eastlake/steps/source_extractor.py#L79

**Comment by beckermr** [comment]
So TL;DR everything now looks correct and we do not have to set analysis_thresh AFAICT.

**Comment by esheldon** [comment]
analysis thresh is not exposed in sep

**Comment by esheldon** [comment]
I think those codes are not run by the `extract` routine

**Comment by beckermr** [comment]
Yup. closing.
